# Eldritch theme
# https://github.com/eldritch-theme/eldritch
# darker #171928
# alt purple #7081D0
[colors]
ansi = [
  '#212337',
  '#F16C75',
  '#37F499',
  '#F7F67F',
  '#A48CF2',
  '#F265B5',
  '#04D1F9',
  '#EBFAFA',
]
background = '#171928'
brights = [
  '#212337',
  '#F9515D',
  '#37F499',
  '#E9F941',
  '#9071F4',
  '#F265B5',
  '#66E4FD',
  '#FFFFFF',
]
compose_cursor = '#F7F67F'
cursor_bg = '#37F499'
cursor_border = '#04D1F9'
cursor_fg = '#171928'
foreground = '#EBFAFA'
scrollbar_thumb = '#37F499'
selection_bg = 'rgba(26.666668% 27.843138% 35.294117% 75%)'
selection_fg = 'rgba(0% 0% 0% 0%)'
split = '#7081D0'

[colors.indexed]

[colors.tab_bar]
background = '#171928'

[colors.tab_bar.active_tab]
bg_color = '#37F499'
fg_color = '#171928'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab]
bg_color = '#171928'
fg_color = '#7081D0'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab_hover]
bg_color = '#212337'
fg_color = '#37F499'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab]
bg_color = '#171928'
fg_color = '#EBFAFA'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab_hover]
bg_color = '#37F499'
fg_color = '#EBFAFA'
intensity = 'Normal'
italic = true
strikethrough = false
underline = 'None'

[metadata]
aliases = []
author = 'jacobrreed'
name = 'Eldritch'
origin_url = 'https://github.com/eldritch-theme/eldritch/ports/terminal/wezterm'
