# Rose Pine Dawn theme (light)
[colors]
ansi = [
  '#f2e9e1',
  '#b4637a',
  '#286983',
  '#ea9d34',
  '#907aa9',
  '#d7827e',
  '#56949f',
  '#575279',
]
background = '#faf4ed'
brights = [
  '#9893a5',
  '#b4637a',
  '#286983',
  '#ea9d34',
  '#907aa9',
  '#d7827e',
  '#56949f',
  '#575279',
]
compose_cursor = '#ea9d34'
cursor_bg = '#d7827e'
cursor_border = '#d7827e'
cursor_fg = '#faf4ed'
scrollbar_thumb = '#907aa9'
foreground = '#575279'
selection_bg = 'rgba(95% 91% 88% 75%)'
selection_fg = 'rgba(0% 0% 0% 0%)'
split = '#9893a5'

[colors.indexed]

[colors.tab_bar]
background = '#f2e9e1'

[colors.tab_bar.active_tab]
bg_color = '#faf4ed'
fg_color = '#575279'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab]
bg_color = '#DCD6D0'
fg_color = '#6A6681'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab_hover]
bg_color = '#d7827e'
fg_color = '#faf4ed'
intensity = 'Normal'
italic = true
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab]
bg_color = '#BAB7B1'
fg_color = '#575279'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab_hover]
bg_color = '#d7827e'
fg_color = '#575279'
intensity = 'Normal'
italic = true
strikethrough = false
underline = 'None'

[metadata]
aliases = []
author = 'Rose Pine'
name = 'rose-pine-dawn'
origin_url = 'https://rosepinetheme.com/'
