  theme:
    activeBorderColor:
      - "#9ece6a"
      - bold
    inactiveBorderColor:
      - "#565f89"
    searchingActiveBorderColor:
      - "#bb9af7"
      - bold
    optionsTextColor:
      - "#7dcfff"
    selectedLineBgColor:
      - "#292e42"
    inactiveViewSelectedLineBgColor:
      - bold
    cherryPickedCommitFgColor:
      - "#bb9af7"
    cherryPickedCommitBgColor:
      - "#7aa2f7"
    markedBaseCommitFgColor:
      - "#7aa2f7"
    markedBaseCommitBgColor:
      - "#e0af68"
    unstagedChangesColor:
      - "#f7768e"
    defaultFgColor:
      - "#c0caf5"
