colourful: true
# WIP Eldritch theme
filekinds:
  normal: { foreground: Default, is_dimmed: true }
  directory: { foreground: Blue, is_bold: true }
  symlink: { foreground: "#f265b5" }
  pipe: { foreground: Yellow }
  block_device: { foreground: Yellow, is_bold: true }
  char_device: { foreground: Yellow, is_bold: true }
  socket: { foreground: Red, is_bold: true }
  special: { foreground: Yellow }
  executable: { foreground: Green, is_bold: true }
  mount_point: { foreground: Blue, is_bold: true, is_underline: true }

file_type:
  image: { foreground: "#04d1f9" }
  video: { foreground: "#39DDFD", is_bold: true }

filenames:
  # Custom filename-based overrides
  # Cargo.toml: {icon: {glyph: ğŸ¦€}}

extensions:
  3mf: { filename: { foreground: "#a48cf2", is_dimmed: true }, icon: { glyph: ğŸ”© } }
  f3d: { filename: { foreground: "#a48cf2", is_dimmed: true }, icon: { glyph: ğŸ“ } }
  step: { filename: { foreground: "#a48cf2", is_dimmed: true }, icon: { glyph: ğŸ“ } }
  stl: { filename: { foreground: "#a48cf2", is_dimmed: true }, icon: { glyph: ğŸŒ€ } }
