dictionaries = [
    "en_us",
    "en_gb",
]
words = [
    "astro",
    "borderless",
    "codebook",
    "codeium",
    "cterm",
    "cursorcolumn",
    "cursorline",
    "esc",
    "heltzel",
    "homebrew",
    "karabiner",
    "keymap",
    "keymaps",
    "lazygit",
    "lilex",
    "lualine",
    "noremap",
    "nvim",
    "rustc",
    "spelllang",
    "swapfile",
    "undodir",
    "undofile",
]
ignore_paths = [
    "target/**/*",
    "**/*.json",
    ".git/**/*",
    "node_modules/**/*",
]
ignore_patterns = [
    '\b[ATCG]+\b',
    '\d{3}-\d{2}-\d{4}',
    "^[A-Z]{2,}$",
    'https?://[^\s]+',
]
