dictionaries = [
    "en_us",
    "en_gb",
]
words = [
    "astro",
    "backhaul",
    "borderless",
    "codebook",
    "codeium",
    "cterm",
    "cursorcolumn",
    "cursorline",
    "deno",
    "esc",
    "fairborn",
    "figma",
    "heltzel",
    "homebrew",
    "karabiner",
    "keymap",
    "keymaps",
    "lazygit",
    "lazyvim",
    "lilex",
    "lualine",
    "neovim",
    "njk",
    "noremap",
    "nvim",
    "qmk",
    "ripgrep",
    "rustc",
    "spelllang",
    "spotify",
    "swapfile",
    "tokyonight",
    "undodir",
    "undofile",
    "wez",
    "wezterm",
    "yazi",
]
ignore_paths = [
    "target/**/*",
    "**/*.json",
    ".git/**/*",
    "node_modules/**/*",
    "nextjs/**/*",
]
ignore_patterns = [
    '\b[ATCG]+\b',
    '\d{3}-\d{2}-\d{4}',
    "^[A-Z]{2,}$",
    'https?://[^\s]+',
]
