dictionaries = [
    "en_us",
    "en_gb",
]
words = [
    "astro",
    "borderless",
    "codebook",
    "esc",
    "heltzel",
    "homebrew",
    "karabiner",
    "keymap",
    "keymaps",
    "lazygit",
    "lualine",
    "noremap",
    "nvim",
    "rustc",
]
ignore_paths = [
    "target/**/*",
    "**/*.json",
    ".git/**/*",
    "node_modules/**/*",
]
ignore_patterns = [
    '\b[ATCG]+\b',
    '\d{3}-\d{2}-\d{4}',
    "^[A-Z]{2,}$",
    'https?://[^\s]+',
]
