dictionaries = ["en_us", "en_gb"]
words = [
  "astro",
  "borderless",
  "codebook",
  "codeium",
  "cterm",
  "cursorcolumn",
  "cursorline",
  "deno",
  "esc",
  "Heltzel",
  "heltzel",
  "homebrew",
  "karabiner",
  "keymap",
  "keymaps",
  "lazygit",
  "lazyvim",
  "lilex",
  "lualine",
  "noremap",
  "nvim",
  "rustc",
  "ripgrep",
  "spelllang",
  "swapfile",
  "undodir",
  "undofile",
  "wezterm",
]
ignore_paths = ["target/**/*", "**/*.json", ".git/**/*", "node_modules/**/*"]
ignore_patterns = [
  '\b[ATCG]+\b',
  '\d{3}-\d{2}-\d{4}',
  "^[A-Z]{2,}$",
  'https?://[^\s]+',
]
