"$schema" = "https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json"
version = 2

[[blocks]]
alignment = "left"
type = "prompt"
newline = true

[[blocks.segments]]
foreground = "cyan"
style = "plain"
template = "<#7DCFFF>\u26a1</>{{ .Path }} "
type = "path"

[blocks.segments.properties]
style = "folder"

[[blocks.segments]]
foreground = "#F141A8"
style = "diamond"
template = "{{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Working.Changed }} <#CF9152> {{ .Working.String }}</>{{ end }}{{ if and (.Working.Changed) (.Staging.Changed) }} |{{ end }}{{ if .Staging.Changed }} ï† {{ .Staging.String }}{{ end }}{{ if gt .StashCount 0 }} ï  {{ .StashCount }}{{ end }} "
type = "git"

[blocks.segments.properties]
branch_icon = "ï˜ "
fetch_stash_count = true
fetch_status = true
fetch_e_count = true

[[blocks.segments]]
type = "aws"
foreground = "#FFA400"
style = "plain"
template = "ï‰° {{.Profile}}{{if .Region}}@{{.Region}}{{end}}"

[[blocks.segments]]
type = "project"
foreground = "#FF7A14"
style = "plain"
template = "{{if .Version}} ó°— {{.Version}} {{end}}"

[[blocks.segments]]
foreground = "darkGray"
style = "plain"
template = "ó±¢ {{ .Full }} "
type = "deno"

[[blocks.segments]]
foreground = "green"
style = "plain"
template = "ó°™ {{ .Full }} "
type = "node"

[[blocks.segments]]
display_mode = "files"
files = ["package-lock.json"]
foreground = "#C00C00"
style = "plain"
template = "îœ {{ .Full }} "
type = "npm"

[[blocks.segments]]
display_mode = "files"
files = ["pnpm-lock.yaml"]
foreground = "#F9AD06"
style = "plain"
template = "ó±‡š {{ .Full }} "
type = "pnpm"

[[blocks.segments]]
display_mode = "files"
files = ["bun.lockb"]
foreground = "#CCBEA7"
style = "plain"
template = "ğŸ¥Ÿ {{ .Full }} "
type = "bun"

[blocks.segments.properties]
fetch_version = true

[[blocks.segments]]
foreground = "#7FD5EA"
style = "plain"
template = "ï†  {{.Full}} "
type = "go"

[[blocks.segments]]
foreground = "blue"
style = "plain"
template = "î˜  {{.Full}} "
type = "lua"

[[blocks.segments]]
foreground = "#4063DB"
style = "plain"
template = "î˜ˆ {{.Full}} "
type = "php"

[[blocks.segments]]
foreground = "#906CFF"
style = "plain"
template = "î˜† {{.Full}} "
type = "python"

[[blocks.segments]]
foreground = "#CF043D"
style = "plain"
template = "ó°´­ {{.Full}} "
type = "ruby"

[[blocks.segments]]
foreground = "#99908A"
style = "plain"
template = "îš‹ {{.Full}} "
type = "rust"


[[blocks.segments]]
foreground = "#CFC9C2"
leading_diamond = "<#CFC9C2>ó°”›</>"
style = "diamond"
template = " {{ .FormattedMs }} "
type = "executiontime"

[blocks.segments.properties]
style = "roundrock"
threshold = 0

[[blocks]]
type = "prompt"
alignment = "left"
newline = true

[[blocks.segments]]
type = "text"
foreground_templates = ["{{ if gt .Code 0 }}#F7768E{{ end }}", "{{ if eq .Code 0}}#9ECE6A{{ end }}"]
style = "plain"
template = "â¯ "

[blocks.valid_line]
background = "transparent"
foreground = "#FFFFFF"
template = "<#E0DEF4,#286983>ï® </><#286983,transparent>î‚´</> "

[blocks.error_line]
background = "transparent"
foreground = "#FFFFFF"
template = "<#EB6F92,#286983>î€‰ </><#286983,transparent>î‚´</> "

[transient_prompt]
foreground = "green"
background = "transparent"
template = "â¯ "
